name: varcore_flutter_base
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  get: ^4.3.8
  dio: ^4.0.4

  # Database
  get_storage: ^2.0.3
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.11
  hive: ^2.2.2

  # Notifications
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  flutter_local_notifications: ^9.3.2
  rxdart: ^0.27.3

  # Pdf
  flutter_pdfview: ^1.2.1
  internet_file: ^1.0.0+2
  pdfx: ^2.0.1+1

  # File Manager
  image: ^3.2.0
  camera: ^0.9.4+11
  photo_manager: ^2.1.2
  image_picker: ^0.8.4+6
  file_picker: ^4.3.1
  flutter_image_compress: ^1.1.0
  video_player: ^2.2.10
  video_compress: ^3.1.0
  open_file: ^3.2.1
  signature: ^5.0.0

  # Others
  webview_flutter: ^3.0.2
  url_launcher: ^6.1.2
  intl: ^0.17.0
  path_provider: ^2.0.8
  fluttertoast: ^8.0.9
  double_back_to_close_app: ^2.0.1
  material_design_icons_flutter: ^5.0.6595
  cupertino_icons: ^1.0.2
  introduction_screen: ^2.1.0
  pin_code_fields: ^7.3.0
  flutter_keyboard_visibility: ^5.2.0
  lottie: ^1.2.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/anim/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Light.ttf
          weight: 300
