name: skybase
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  get: ^4.6.5
  dio: ^5.2.1+1

  # Database
  get_storage: ^2.1.1
  flutter_secure_storage: ^8.0.0
  hive: ^2.2.3

  # File Manager
  android_path_provider: ^0.3.0
  image: ^4.0.17
  camera: ^0.10.5+2
  photo_manager: ^2.6.0
  image_picker: ^0.8.9
  file_picker: ^5.3.2
  flutter_image_compress: ^2.0.3
  chewie: ^1.5.0
  video_player: ^2.6.1
  cached_network_image: ^3.2.3
  path: ^1.8.3

  # Widget
  carousel_slider: ^4.1.1
  modal_bottom_sheet: ^3.0.0-pre
  infinite_scroll_pagination: ^3.2.0
  shimmer: ^2.0.0
  calendar_date_picker2: ^0.3.6
  cupertino_icons: ^1.0.5
  lottie: ^2.2.0
  flutter_svg: ^1.1.6
  introduction_screen: ^3.1.4
  dotted_border: ^2.0.0+3

  # Others
  collection_picker: ^0.0.2+3
  package_info_plus: ^3.0.2
  device_info_plus: ^9.0.2
  url_launcher: ^6.1.7
  permission_handler: ^10.2.0
  intl: ^0.18.0
  path_provider: ^2.0.11
  double_back_to_close_app: ^2.1.0
  internet_file: ^1.2.0
  open_filex: ^4.3.2
  mask_text_input_formatter: ^2.4.0
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  rename: ^2.1.1
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.4.5
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  win32: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/anim/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Light.ttf
          weight: 300

#flutter_icons:
#  image_path: "assets/images/logo/app_logo.png"
#  min_sdk_android: 21
#  ios: true
#  android: true