name: skybase
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  get: ^4.3.8
  dio: ^4.0.4

  # Database
  get_storage: ^2.0.3
  flutter_secure_storage: ^5.0.2
  hive: ^2.2.2

  # Notifications
  socket_io_client: ^2.0.0
  flutter_local_notifications: ^9.3.2
  rxdart: ^0.27.3

  # File Manager
  image: ^3.2.0
  camera: ^0.10.0+1
  photo_manager: ^2.1.2
  image_picker: ^0.8.4+6
  file_picker: ^5.0.1
  flutter_image_compress: ^1.1.0

  # Widget
  modal_bottom_sheet: ^2.1.0
  infinite_scroll_pagination: ^3.2.0
  shimmer: ^2.0.0
  calendar_date_picker2: ^0.2.2
  cupertino_icons: ^1.0.2
  lottie: ^1.2.1
  flutter_svg: ^1.1.0
  fluttertoast: ^8.0.9
  webview_flutter: ^3.0.2
  introduction_screen: ^2.1.0
  pin_code_fields: ^7.3.0
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.1

  # Others
  package_info_plus: ^1.4.3+1
  url_launcher: ^6.1.5
  permission_handler: ^10.0.0
  intl: ^0.17.0
  path_provider: ^2.0.8
  double_back_to_close_app: ^2.0.1
  rename: ^2.0.1
  internet_file: ^1.0.0+2
  open_filex: ^4.0.1
  mask_text_input_formatter: ^2.4.0 # Masking FormTextField

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/anim/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Light.ttf
          weight: 300

#flutter_icons:
#  image_path: "assets/images/logo/app_logo.png"
#  min_sdk_android: 21
#  ios: true
#  android: true