name: skybase
description: Code base for flutter using getx.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0-alpha.1+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Architecture
  get: ^4.6.6
  dio: ^5.3.4
  json_annotation: ^4.8.1
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^4.0.2
#  sliver_tools: ^0.2.12

  # File Manager
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  flutter_image_compress: ^2.1.0
  path: ^1.8.3

  # Widget
  modal_bottom_sheet: ^3.0.0-pre
  infinite_scroll_pagination: ^4.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9

  # Others
  package_info_plus: ^4.2.0
  device_info_plus: ^9.0.2
  url_launcher: ^6.2.1
  permission_handler: ^11.1.0
  intl: ^0.19.0
  open_filex: ^4.3.4
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.2.8
#  change_app_package_name: ^1.1.0
#  rename: ^2.1.1
#  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Light.ttf
          weight: 300

#
# Usage :
# flutter pub run flutter_launcher_icons
#
#flutter_icons:
#  image_path: "assets/images/logo/app_logo.png"
#  min_sdk_android: 21
#  ios: true
#  android: true
#  remove_alpha_ios: true (Optional)
#  background_color_ios: "#ffffff" (Optional)